# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1 # Skip downloading during yarn install
  PLAYWRIGHT_BROWSERS_PATH: 0 # Places binaries to node_modules/@playwright/test

jobs:
  e2e:
    runs-on: ubuntu-latest
        

    steps:
      - name: set path
        uses: ./
        
      - name: Install dependencies
        run: |
            npx playwright install-deps
        
      - name: Setup
        
        run: |
            npm install
            npx playwright install
            
      - name: test
        run: |
            npm test
